{% set name = "the-segmentation-game" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/the-segmentation-game-{{ version }}.tar.gz
  sha256: 4bbf4deadecb84efc893c6cea2d51e90374181589f2034050aa3cf8fa65872f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops
    - napari-tools-menu
    - numpy
    - python >=3.7
    - scikit-learn

test:
  imports:
    - the_segmentation_game
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/the-segmentation-game
  summary: Gamified image segmentation quality estimation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
